### ISSUE TITLE
你好，有点问题特来请教

### ISSUE THREAD

**Issue by liumin1128** [lyingd/antd-pro-standalone#1]
我参考了你的代码，成功让persist工作了一段时间，但最近代码并没有变化，却发生了很多诡异的事情。
![image](https://user-images.githubusercontent.com/12379461/37580450-b23d6954-2b7e-11e8-9e18-e7f469fa67e4.png)
redux里没有reduer，要么就是无法更新redux

**Comment by liumin1128** [comment]
好好的出异常

**Comment by lyingd** [comment]
可否提供一个最小可重现demo？
